unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded!"

unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

set -g default-terminal "tmux-256color"
set -s terminal-features "xterm-ghostty:RGB:sync:usstyle:extkeys:clipboard:ccolour:cstyle:focus:hyperlinks:osc7:overline:strikethrough:title"
set -g prefix C-a

set -g focus-events on
set -s escape-time 0
set -g allow-passthrough on

set -g mouse on
set -g set-clipboard on

set -g automatic-rename on
set -g allow-rename off
set -g renumber-windows on
set -g detach-on-destroy off

set -g base-index 1
set -g pane-base-index 1

set -g mode-keys vi
set -g status-keys vi
set -g status-right-length 100

set -g history-limit 50000

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "tmux-plugins/tmux-continuum"
set -g @plugin "christoomey/vim-tmux-navigator"
set -g @plugin "catppuccin/tmux"
set -g @plugin "omerxx/tmux-sessionx"
set -g @plugin "xsmyile/tmux-claude-status"
set -g @claude-status-popup-border "rounded"

set -g @sessionx-bind 'o'
set -g @sessionx-filter-current 'true'
set -g @sessionx-preview-enabled 'false'
set -g @sessionx-bind-select-up 'ctrl-k'
set -g @sessionx-bind-select-down 'ctrl-j'

set -g @resurrect-capture-pane-contents "off"

set -g @continuum-restore "on"
set -g @continuum-save-interval "15"

set -g @catppuccin_flavor "macchiato"
set -g @catppuccin_host_color "#89CFF0"
set -g @catppuccin_session_icon "󰆍 "
set -g @catppuccin_directory_icon "󰉖 "
set -g @catppuccin_host_icon "󱓟 "
set -g @catppuccin_window_text " #{pane_current_command}"
set -g @catppuccin_window_current_text " #{pane_current_command}"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_status_background "none"

set -g popup-style 'bg=default'
set -g popup-border-style 'bg=default'

set -g status-left ""

run "~/.config/tmux/tpm/tpm"

run-shell "~/.config/tmux/fix-transparent-pills.sh"
run-shell "~/.config/tmux/bell-accent.sh"

source -F "#{d:current_file}/claude_status.conf"
set -g status-right "#{E:@catppuccin_status_claude_status}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_directory}"
set -ag status-right "#{E:@catppuccin_status_host}"
